cc_binary(
    name = "rustc_wrapper",
    srcs = ["rustc_wrapper.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//rust/private/rustc_wrapper/third_party/microtar",
        "//rust/private/rustc_wrapper/third_party/tiny-process-library",
    ],
)
